app: fastgo

---
profile: dev

port: 8001
mode: debug

session:
  name: "nft_session"
  secret: "b956160659554dbcb0ae65e2f7d5de14"

assets: http://localhost:3000

oauth:
  accessKey: be3393bed417d0fd
  secretKey: b723f7a6aa9342b199361c3600abe738

redis:
  addr: localhost:6379
  db: 0
  poolSize: 100
  minIdleCount: 20

mysql:
  dsn: nft:Aa505814@tcp(localhost:3306)/nft?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleCount: 32
  maxOpenCount: 128
  maxLifetime: 7200

rs:
  prefix: MQ_
  sender:
    maxLen: 100
  receive:
    work: 100
    readCount: 10
    blockTimeSecond: 20
    maxRetries: 3
    timeoutSecond: 300
---
profile: test
port: 8002
mysql:
  dsn: test:test123@tcp(localhost:3306)/nft?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleCount: 32
  maxOpenCount: 128
  maxLifetime: 7200