app: helloword
port: 8001

middleware:
  - recover:
  - limiter:
      rate: 10
      burst: 200
      timeout: 5s
  - ready:
  - logger:
  - monitor:
  - swagger:
      path: "/doc/*"
      json: "./api/helloword/swagger.json"
      mode: "redoc"

session:
  name: "session"
  secret: "b956160659554dbcb0ae65e2f7d5de14"

oauth:
  accessKey: be3393bed417d0fd
  secretKey: b723f7a6aa9342b199361c3600abe738

---
env: dev

redis:
  addr: kubernetes.docker.internal:6379
  db: 0
  poolSize: 100
  minIdleCount: 20

mysql:
  dsn: nft:Aa505814@tcp(localhost:3306)/nft?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleCount: 32
  maxOpenCount: 128
  maxLifetime: 7200

rs:
  prefix: MQ_
  sender:
    maxLen: 100
---
env: test

redis:
  addr: kubernetes.docker.internal:6379
  db: 0
  poolSize: 100
  minIdleCount: 20

mysql:
  dsn: nft:Aa505814@tcp(localhost:3306)/nft?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleCount: 32
  maxOpenCount: 128
  maxLifetime: 7200

---
env: prod

redis:
  addr: kubernetes.docker.internal:6379
  db: 0
  poolSize: 100
  minIdleCount: 20

mysql:
  dsn: test:test123@tcp(localhost:3306)/nft?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleCount: 32
  maxOpenCount: 128
  maxLifetime: 7200